<li><a href="#">Home</a></li>
<li><a href="#">Programme</a></li>
<li><a href="#">Buildings &amp; Tours</a></li>
<li><a href="#">Map</a></li>
<li><a href="#">Event Planner</a></li>
<li><a href="#">About</a></li>
<li><a href="#">Get Involved</a></li>
<li><a href="#">News</a></li>
<li><a href="#">Partners</a></li>
<li><a href="#">Contact</a></li>