language: ruby
rvm:
- 2.2.3
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
branches:
  only:
  - gh-pages
env:
  global:
  - ENCRYPTION_LABEL: "7fb9f9a931ce"
  - COMMIT_AUTHOR_EMAIL: "github@markcrossfield.co.uk"
  - secure: KyaHhOMG/lezF7SJqLCf0omSun6xssyltg8rNf3sUJ3A+sYpU/r36Hy7ohpPO2UKrXDSqmzuk4kDeeBXQSZMKA0u/2pd+ulsvTZmB1zSc1xhUk+p/yDaPmO1aQNc3qsCEa5OzlQlQOzx5YygQ+DxRLDmCdIYl+In/6fzte+nFI0q4RXk4N3xJafHvhCrUisoEi4f+RSuAac4Xp7uiuIhjk+1HA8+AlPlQSHMZyThXjOz3wir44sSFgA8Q36t048on7z7Lpq9hMChZPJDKg6ueXl8SRzgWaE3Bud703cxV0GT5bJ08DBGyT2wX/px7L2qEQ5Hm23z1Pa8QVmG5QBclQcjEZSY1OkHHmmqfhk1do75MWi6WqD6WCOw9ZDfR7Yy77vLsDA8of2i/JeR9Wih7OkbGSqyUnl0P/XozXUhYsg5zxNPmXVM+MJdVjZ7urzerQedRShi1zwMWLENYAu9YGszfd2Kg3sT9Bhlwsit7astEl6ACYlE2v3/ML4z7NXnes1dbIEg25YMnZiVAQBBbFBf+cRcAKHb9wcXpIC6+WSAWxG36BXns7RA2gPF3cx5cLbTBS4ydfKlpTh340P/pfhYVPxJOkEwTXrl/Obafjqv4DyQ2AQ9UC1kdcWg4qIJfpWDx8MT1pddxKiDgwBdi5l3hgFLkEewdwE15DhxMPw=
  - secure: "FLfsUQqRVBkbLY7eBxexASWtPMdhjlv9JpnhMiAzUT903ti2loyvjcIz4Edn3n+OAbTdWiLXKCmQZc2M4/nRrezKKD9YWUHva2Ge33r0v52A2wGzmld22SWjm7bOWW3DtupwfDX7POPx2SiI5mSMiRyRrg2kkjTaPlag7M6DK/XMk2SSL/2hhIF4yGpLgvRurKKk4UAr0/co2Mm3QSq8VH3yfK0eh6FKtQSUfqdky+mapNsQ9PZsN4ivsLCgMSC3b6dKokaHH7VPHOMd3D6dEjJFzGUPC7efkswISpgUc39thJZLNGPlcc4itXtWCUwoUfAjj7naBd5UjHZ+L0uAF+WCGVUlHK5JS+uEentVu6o9ePiEqOJvKkbKhFDmpwfGIookQ+7KhhRoqIIlh/IaN6dc8JAqAH9GgJKOmbvw1SOGg2Wp4Fs0/GR4lS0alFtnCClhGm3RpvjzQ6od7iJ802UMXrDOAPD5lPH94/nONHIkmUABUJXkn7AxJ0dwZwYY7UXW+J5oWXquVp1/YBCPLgw5QQ7T0jPYjuqQJN8VoGRRE8/n8z/9RScPwn/uLMo2lMI5A5f61b71KMhzdbbyv3W9we5kMBONiy8xllUhx0+uzDoYRphatSY40JbT+vt8A326BMS1RpEf/wAOCT9PxVk9COJhhe8Bs7+RwSuuMIQ="
sudo: false
after_success: cd _site && find . -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs
  -T {} ftp://ftp.manchestercurious.com/manchestercurious.com/public_html/showcase/{}
  \;
